export enum Screen {
  TITLE_AJAX = "title-ajax",
  LOGIN = "login",
  LOGIN_AJAX = "login-ajax",
  FORGOT = "forgot",
  FORGOT_AJAX = "forgot-ajax",
  REGISTER = "register",
  REGISTER_AJAX = "register-ajax",
  UPDATING = "updating",
  LOBBY = "lobby",
  RACE = "race",
  ERROR = "error",
  WARNING = "warning",
  WAITING_FOR_SERVER = "waiting-for-server",
  TRANSITION = "transition",
  NULL = "null",
}
