unused_args = false

-- These are from the "enums.lua" file in the "scripts" subdirectory
globals = {
    "ButtonAction",
    "CacheFlag",
    "Card",
    "Challenge",
    "CollectibleType",
    "Color",
    "Direction",
    "EffectVariant",
    "EntityCollisionClass",
    "EntityType",
    "FamiliarVariant",
    "Game",
    "GridEntityType",
    "GridRooms",
    "Input",
    "Isaac",
    "Keyboard",
    "LevelCurse",
    "LevelStage",
    "ModCallbacks",
    "PickupVariant",
    "PillEffect",
    "PlayerType",
    "RandomVector",
    "RegisterMod",
    "RNG",
    "RoomType",
    "SeedEffect",
    "SFXManager",
    "SoundEffect",
    "Sprite",
    "StageType",
    "TrinketType",
    "Vector",
}
